### ISSUE TITLE
Unable to install on 1.3.15

### ISSUE THREAD

**Issue by neuman1812** [idlesign/deluge-webapi#15]
Deluge Web version 1.3.15

Installed on Debian Stretch, Raspberry pi 

Error log:

[ERROR   ] 13:25:39 json_api:240 Error calling method `web.upload_plugin`
[ERROR   ] 13:25:39 json_api:241 [Errno 21] Is a directory: u'/home/vpn/.config/deluge/plugins/'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 232, in _handle_request
    result = self._exec_local(method, params, request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 199, in _exec_local
    return meth(*params)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 1000, in upload_plugin
    shutil.copyfile(path, os.path.join(get_config_dir(), "plugins", filename))
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 21] Is a directory: u'/home/vpn/.config/deluge/plugins/'

**Comment by idlesign** [comment]
Have you tried installing any other plugin, to confirm this one is really related to webapi?

**Comment by idlesign** [comment]
Closed due to inactivity.
