### ISSUE TITLE
1.3.12: can't send even a simple json to the endpoint

### ISSUE THREAD

**Issue by sokoow** [idlesign/deluge-webapi#17]
so I'm trying to follow the docs and do this simple thing:

```
curl -X POST -d '{"id":"1", “method”: “auth.login”, “params”: [“your_password_here”]}}'  -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:8112/json
```

and I get something like this in a 500:

```
[ERROR   ] 10:25:21 json_api:271 JSON not decodable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 293, in render
    d = self._on_json_request(request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 257, in _on_json_request
    response["id"], d, response["error"] = self._handle_request(request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 208, in _handle_request
    raise JSONException("JSON not decodable")
JSONException: JSON not decodable
```

am I doing something wrong ?

**Comment by idlesign** [comment]
It seems that docs render is wrong for quotes: replace ``“`` with  simple ``"``.

**Comment by sokoow** [comment]
Still same :/

**Comment by idlesign** [comment]
This exception indicates you've sent a wrong json, it's not related to to ``webapi`` per se.
You can start with empty JSON ``{}`` and add items one by one to investigate what cases the error.

**Comment by sokoow** [comment]
if I send:

```
curl -X POST -d '{}'  -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:8112/json
```

I still get: 

```
[ERROR   ] 10:45:02 json_api:271 Invalid JSON request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 293, in render
    d = self._on_json_request(request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 257, in _on_json_request
    response["id"], d, response["error"] = self._handle_request(request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 212, in _handle_request
    raise JSONException("Invalid JSON request")
JSONException: Invalid JSON request
```

**Comment by idlesign** [comment]
You may deep into Deluge and see what's in ``request.json.decode()``:
https://github.com/deluge-torrent/deluge/blob/develop/deluge/ui/web/json_api.py#L140

**Comment by idlesign** [comment]
For an example using ``requests`` you can refer to https://github.com/idlesign/deluge-webapi/blob/master/webapi/test.py
Closing this.
